### ISSUE TITLE
Google Social Login (backend)

### ISSUE THREAD

**Issue by Malte2036** [Malte2036/react-social-backend#1]

**Comment by Malte2036** [comment]
Also see: https://github.com/Malte2036/react-social/issues/2

**Comment by spykelionel** [comment]
Oh. This looks good too

**Comment by Malte2036** [comment]
https://github.com/Malte2036/react-social/issues/2#issuecomment-1271355889

**Comment by anubhav2102** [comment]
Can i work on this issue?

**Comment by Malte2036** [comment]
Yes, but take a look at https://github.com/Malte2036/react-social/issues/2#issuecomment-1271355889
